### PR TITLE
generate index.md

### LINKED ISSUE #7: Generate index.md from template
Manual updates to index.md become very tedious as the number of sheets will grow greatly. We need a index.md generator script.

### PR DESCRIPTION
**Pull request by carlinmack**
closes #7

### CODE REVIEW

**Comment by carlinmack** [comment]
when merging change line 3 to `const index_md = 'index.md'`

**Comment by carlinmack** [comment]
If we generate the files to be like:

smileys-emotion-0.png
smileys-emotion-1.png
...

Then this can be extended to any number of stylesheets

**Comment by carlinmack** [comment]
Once this and the generator are stable enough we should probably do a github release and direct people to download that instead

**Comment by axelpale** [comment]
Thank you, great stuff!

**Comment by carlinmack** [comment]
The site looks great now! 

btw you can remove the extra `# openmoji-sprites` at the top of the generator, I didn't realise that the header is added somewhere else

**Pull request merged**
